name: Docker Container Check
on:
  push:
    branches:
      - master 

jobs:
  check_docker_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t qmcgaw/latexdevcontainer:latest ../.devcontainer/Dockerfile

      - name: Run Docker Container
        run: docker run -d --name test_container qmcgaw/latexdevcontainer:latest

      - name: Check Container Status
        id: check_status
        run: |
          container_status=$(docker inspect -f '{{.State.Status}}' test_container)
          if [[ "$container_status" == "running" ]]; then
            echo "::set-output name=container_status::running"
          else
            echo "::set-output name=container_status::failed"
          fi

      - name: Stop Docker Container
        run: docker stop test_container

      - name: Clean Up Docker Container
        run: docker rm test_container
