name: docker-resume-template
on: [push]
jobs:
  check-conatainer:
    runs-on: ubuntu-latest
    container: qmcgaw/latexdevcontainer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build .
